# Generated by Django 4.2 on 2023-04-13 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_book_contributors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='contributors',
        ),
    ]
