# Generated by Django 4.2 on 2023-04-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_remove_contributor_contributors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(help_text='The name of the Publisher.', max_length=50, verbose_name="Name's Publisher"),
        ),
    ]
