# Generated by Django 4.2 on 2023-04-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_publisher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='email',
            field=models.EmailField(blank=True, help_text="The Publisher's email address.", max_length=254, null=True),
        ),
    ]
